# Generated by Django 5.2.1 on 2025-06-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(unique=True, null=True),
        ),
    ]
