# Generated by Django 5.2.1 on 2025-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
