# Generated by Django 5.2.1 on 2025-06-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankDetail',
            new_name='Bank',
        ),
    ]
