# Generated by Django 5.2.1 on 2025-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_rename_bankdetail_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
