# Generated by Django 5.2.1 on 2025-06-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
        migrations.AddField(
            model_name='employee',
            name='sslug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
