# Generated by Django 5.2.1 on 2025-06-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_slug_employee_sslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='sslug',
            new_name='slug',
        ),
    ]
